#!/usr/bin/env bash
# Transfers a file to a remote server using scp with a given private key

# === Check if all required parameters are passed ===
if [ "$#" -ne 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# === Assign variables from arguments ===
FILE="$1"
SERVER_IP="$2"
USERNAME="$3"
KEY_PATH="$4"

# === Use scp to transfer file ===
scp -i "$KEY_PATH" -o StrictHostKeyChecking=no "$FILE" "$USERNAME@$SERVER_IP:~/"
